apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-server.fullname" . }}
  labels:
    {{- include "cloud-server.labels" . | nindent 4 }}
data:
  rc.env: {{ .Values.rcEnv }} 
  rc.local: {{ .Values.rcLocal }} 
