homeSize: 2Gi
#homeStorageClassName: my-sc

user: human 
userID: 10000
hostName: "myserver"
userSSHKey: ""
userSSHImport: ""
customizeRepo: ""
customizeRepoCommand: ""
customizeCommand: ""
privileged: true 

extraPorts: []
  #- port: 80
  #  proto: TCP
  #  name: http
  #- port: 443
  #  proto: TCP
  #  name: https  

extraMounts: []
  #- name: cis90
  #  path: /home/cis90
  #  size: 1Gi 
  #  className: hdd
  #- name: cis91
  #  path: /home/cis91
  #  size: 1Gi 
  #  className: hdd

ssh:
  sshd_config: |
    Include /etc/ssh/sshd_config.d/*.conf
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    UsePAM yes
    X11Forwarding yes
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem	sftp	/usr/lib/openssh/sftp-server
    TrustedUserCAKeys /etc/ssh/ca/ca_key.pub
    HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub

rcEnv: |
  # Extra variables for startup here.

rcUser: |
  #! /usr/bin/bash
  set -e 

  # Load the SSH key
  if [ ! -z "${DEFAULT_KEY}" ]; then
      mkdir -p ~/.ssh
      echo ${DEFAULT_KEY} > ~/.ssh/authorized_keys
  fi

  # Load account SSH keys
  if [ ! -z "${DEFAULT_KEY_IMPORT}" ]; then
      /usr/bin/ssh-import-id ${DEFAULT_KEY_IMPORT}
  fi 

  # Customize by repo
  if [ ! -z "${CUSTOMIZE_REPO}" ]; then 
    tempdir=$(mktemp -d)
    git clone --recurse-submodules ${CUSTOMIZE_REPO} $tempdir
    (
      cd $tempdir
      bash -c "$CUSTOMIZE_REPO_COMMAND" || true
    )
    rm -rf $tempdir 
  fi 

  # Customize by command
  (
    cd /home/$DEFAULT_USER
    if [ ! -z "$CUSTOMIZE_COMMAND" ]; then 
      bash -c "$CUSTOMIZE_COMMAND" 
    fi 
  )


rcLocal: |
  #! /usr/bin/bash
  set -e 

  . /etc/rc.env 
  
  # System setup 
  echo "127.0.1.1 ${SET_HOSTNAME}" | tee -a /etc/hosts 
  echo "${SET_HOSTNAME}" | tee /etc/hostname 
  hostname ${SET_HOSTNAME} || true  # Doesn't work in unpriveleged containers.

  # User setup
  groupadd ${DEFAULT_USER} -g ${DEFAULT_USER_ID}
  useradd ${DEFAULT_USER} -u ${DEFAULT_USER_ID} -g ${DEFAULT_USER} -G adm -m -s /usr/bin/bash
  echo "${DEFAULT_USER} ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/${DEFAULT_USER}
  chown ${DEFAULT_USER}:${DEFAULT_USER} /home/${DEFAULT_USER}

  # User customization
  tempfile=$(mktemp)
  cp /etc/rc.user $tempfile 
  chown ${DEFAULT_USER}:${DEFAULT_USER} $tempfile 
  chmod u+x $tempfile
  su ${DEFAULT_USER} -c "$tempfile" || true
  rm $tempfile

  touch /ready

image:
  repository: ghcr.io/mike-matera/cloud-server-ubuntu-jammy
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

pvcAnnotations:
  helm.sh/resource-policy: "keep"

service:
  type: LoadBalancer
  # loadBalancerIP: 10.0.0.100
  port: 22
  annotations: {}
  #  metallb.universe.tf/allow-shared-ip: cloud-share-key

resources: 
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
