homeSize: 2Gi
#homeStorageClassName: my-sc

user: human 
hostName: "myserver"
userSSHKey: ""
userSSHImport: ""
customizeCommand: "bin/init.sh"
privileged: true 

extraPorts: []
  #- port: 80
  #  proto: TCP
  #  name: http
  #- port: 443
  #  proto: TCP
  #  name: https  

extraMounts: []
  #- name: cis90
  #  path: /home/cis90
  #  size: 1Gi 
  #  className: hdd
  #- name: cis91
  #  path: /home/cis91
  #  size: 1Gi 
  #  className: hdd

ssh:
  sshd_config: |
    Include /etc/ssh/sshd_config.d/*.conf
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    UsePAM yes
    X11Forwarding yes
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem	sftp	/usr/lib/openssh/sftp-server
    TrustedUserCAKeys /etc/ssh/ca/ca_key.pub
    HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub

rcEnv: |
  # Extra variables for startup here.

rcLocal: |
  #! /usr/bin/bash
  set -e 

  . /etc/rc.env 
  
  # System setup 
  echo "127.0.1.1 ${SET_HOSTNAME}" | tee -a /etc/hosts 
  echo "${SET_HOSTNAME}" | tee /etc/hostname 
  hostname ${SET_HOSTNAME} || true  # Doesn't work in unpriveleged containers.

  # User setup
  useradd ${DEFAULT_USER} -u 1000 -U -G adm -m -s /usr/bin/bash
  echo "${DEFAULT_USER} ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/${DEFAULT_USER}
  chown ${DEFAULT_USER}:${DEFAULT_USER} /home/${DEFAULT_USER}
  if [ ! -z "${DEFAULT_KEY}" ]; then
      su ${DEFAULT_USER} -c "mkdir -p ~/.ssh; echo ${DEFAULT_KEY} > ~/.ssh/authorized_keys"
  fi 
  if [ ! -z "${DEFAULT_KEY_IMPORT}" ]; then
      su ${DEFAULT_USER} -c "/usr/bin/ssh-import-id ${DEFAULT_KEY_IMPORT}"
  fi 

  # User customization
  (
    cd /home/$DEFAULT_USER
    if [ -f "$CUSTOMIZE_COMMAND" ]; then 
      su ${DEFAULT_USER} -c "$CUSTOMIZE_COMMAND"
    fi 
  )

  touch /ready

image:
  repository: ghcr.io/mike-matera/cloud-native-server
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: LoadBalancer
  # loadBalancerIP: 10.0.0.100
  port: 22
  annotations: {}
  #  metallb.universe.tf/allow-shared-ip: cloud-share-key

resources: 
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
