---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-server.fullname" . }}
  labels:
    {{- include "cloud-server.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.homeSize }}
  {{- if hasKey .Values "homeStorageClassName" }}
  storageClassName: {{ .Values.homeStorageClassName }}
  {{- end }}

