apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-server.fullname" . }}
  labels:
    {{- include "cloud-server.labels" . | nindent 4 }}
data:
  rc.env: |
    export DEFAULT_USER="{{ .Values.user }}" 
    export DEFAULT_KEY="{{ .Values.userSSHKey }}"
    export DEFAULT_KEY_IMPORT="{{ .Values.userSSHImport }}"
    export SET_HOSTNAME="{{ .Values.hostName }}"
    export CUSTOMIZE_COMMAND="{{ .Values.customizeCommand }}"
    {{ .Values.rcEnv | nindent 4 }}
  rc.local: | 
    {{- .Values.rcLocal | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-server.fullname" . }}-ssh
  labels:
    {{- include "cloud-server.labels" . | nindent 4 }}
data:
  sshd_config: | 
    {{- .Values.ssh.sshd_config | nindent 4 }}
  genkey.sh: | 
    #! /usr/bin/bash 

    . /etc/rc.env 

    # SSH setup
    ssh-keygen -A 
    ssh-keygen -s /etc/ssh/ca/ca_key -I ${SET_HOSTNAME} -h /etc/ssh/ssh_host_rsa_key.pub

    # Hide the secret key in the production container
    cp -Lr /etc/ssh/* /workdir 
    rm -rf /workdir/ca/ca_key /workdir/ca/..?*
