apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-server.fullname" . }}
  labels:
    {{- include "cloud-server.labels" . | nindent 4 }}
data:
  rc.env: |
    DEFAULT_USER="{{ .Values.user }}" 
    DEFAULT_KEY="{{ .Values.userSSHKey }}"
    DEFAULT_KEY_IMPORT="{{ .Values.userSSHImport }}"
    SET_HOSTNAME="{{ .Values.hostName }}"
    CUSTOMIZE_REPO="{{ .Values.customizeRepo }}"
    CUSTOMIZE_CMD="{{ .Values.customizeCommand }}"
    {{ .Values.rcEnv | nindent 4 }}

  rc.local: | {{ .Values.rcLocal | nindent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-server.fullname" . }}-ssh
  labels:
    {{- include "cloud-server.labels" . | nindent 4 }}
data:
  ca_key.pub: | {{ .Values.ssh.ca_key_pub | nindent 4 }}
  sshd_config: | {{ .Values.ssh.sshd_config | nindent 4 }}
