apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-server.fullname" . }}
type: Opaque
stringData:
  ca_key: | 
    {{- .Values.ssh.ca_key | nindent 4 }}
  ca_key.pub: | 
    {{- .Values.ssh.ca_key_pub | nindent 4 }}
