apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-server.fullname" . }}
  labels:
    {{- include "cloud-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if hasKey .Values.service "loadBalancerIP" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
    {{- range .Values.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .proto }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "cloud-server.selectorLabels" . | nindent 4 }}
