apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cloud-server.fullname" . }}
  labels:
    {{- include "cloud-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cloud-server.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "cloud-server.fullname" . }}
  replicas: 1
  minReadySeconds: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloud-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloud-server.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      volumes:
        - name: sshsecret
          secret:
            secretName: {{ include "cloud-server.fullname" . }}
            defaultMode: 0400
        - name: sshconfig
          configMap:
            name: {{ include "cloud-server.fullname" . }}-ssh
            defaultMode: 0444
        - name: config
          configMap:
            name: {{ include "cloud-server.fullname" . }}
            defaultMode: 0500
      containers:
        - name: {{ .Chart.Name }}
          tty: true
          stdin: true
          {{- if .Values.privileged }}
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
          {{- else }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: true
          command: ["/usr/bin/bash"]
          args: ["-c", "mkdir /run/sshd; /etc/rc.local; touch /ready; exec /usr/sbin/sshd -e -D"]
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: container
              value: other
          volumeMounts:
            - name: sshsecret
              mountPath: "/etc/ssh/ca/ca_key"
              subPath: "ca_key"
            - name: sshsecret
              mountPath: "/etc/ssh/ca/ca_key.pub"
              subPath: "ca_key.pub"
            - name: sshconfig
              mountPath: "/etc/ssh/sshd_config"
              subPath: "sshd_config"
            - name: config
              mountPath: "/etc/rc.local"
              subPath: "rc.local"
            - name: config
              mountPath: "/etc/rc.env"
              subPath: "rc.env"
            - name: home
              mountPath: "/home"
            {{- range .Values.extraMounts }}
            - name: {{ .name }}
              mountPath: {{ .path }}
            {{- end }}
          ports:
            - containerPort: 22
            {{- range .Values.extraPorts }}
            - containerPort: {{ .port }}
              name: {{ .name }}
              protocol: {{ .proto }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 22
            failureThreshold: 2
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
              - cat
              - /ready
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: home
        labels:
          {{- include "cloud-server.labels" . | nindent 10 }}
        annotations:
          helm.sh/resource-policy: "keep"
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ .Values.homeSize }}
        {{- if hasKey .Values "homeStorageClassName" }}
        storageClassName: {{ .Values.homeStorageClassName }}
        {{- end }}
    {{- range .Values.extraMounts }}
    - metadata:
        name: {{ .name }}
        annotations:
          helm.sh/resource-policy: "keep"
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ .size }}
        {{- if hasKey . "className" }}
        storageClassName: {{ .className }}
        {{- end }}
    {{- end }}    
